config/routes.rb
Sequent::Engine.routes.draw do
  resources :events, only: [:index, :show]
  resources :commands, only: [:show]
  resources :streams, only: [:index, :show] do
    resources :events, only: [:index]
  end
end

app/models/sequent/application_record.rb
module Sequent
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/controllers/sequent/application_controller.rb
module Sequent
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/sequent/commands_controller.rb
require_dependency "sequent/application_controller"

module Sequent
  class CommandsController < ApplicationController
    def index
      @commands = Sequent::Core::CommandRecord.all.order(id: :desc)
    end

    def show
      @command = Sequent::Core::CommandRecord.find(params[:id])
    end
  end
end

app/controllers/sequent/events_controller.rb
require_dependency "sequent/application_controller"

module Sequent
  class EventsController < ApplicationController
    def index
      @grouped_events = get_events.limit(100).order(id: :desc).includes(:command_record).group_by(&:command_record)
    end

    def show
      @event = Sequent::Core::EventRecord.find(params[:id])
    end

    private

    def get_events
      if params[:stream_id].present?
        Sequent::Core::StreamRecord.find(params[:stream_id]).event_records
      else
        Sequent::Core::EventRecord.all
      end
    end
  end
end

app/controllers/sequent/streams_controller.rb
require_dependency "sequent/application_controller"

module Sequent
  class StreamsController < ApplicationController
    def index
      @streams = get_streams.order(id: :desc)
    end

    private

    def get_streams
      if params[:aggregate_type].present?
        Sequent::Core::StreamRecord.where(aggregate_type: params[:aggregate_type])
      else
        Sequent::Core::StreamRecord.all
      end
    end
  end
end

app/helpers/sequent/application_helper.rb
module Sequent
  module ApplicationHelper
  end
end

app/helpers/sequent/events_helper.rb
module Sequent
  module EventsHelper
  end
end

app/views/layouts/sequent/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
        <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <title>Sequent rails</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag    "sequent/application", media: "all" %>


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- Leave those next 4 lines if you care about users using IE8 -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class='container'>
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <%= link_to "Streams", streams_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Events", events_path, class: 'nav-link' %>
        </li>
      </ul>
      <%= yield %>
    </div>

    <!-- Including Bootstrap JS (with its jQuery dependency) so that dynamic components work -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/layouts/sequent/rails/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sequent rails</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    "sequent/rails/application", media: "all" %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sequent/commands/show.html.erb
<table class="table table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Attribute</th>
      <th scope="col">Value</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <th scope="row">id</th>
      <td><%= @command.id %></td>
    </tr>

    <tr>
      <th scope="row">Type</th>
      <td><%= @command.command_type %></td>
    </tr>

    <tr>
      <th scope="row">User</th>
      <td><%= @command.user_id %></td>
    </tr>

    <tr>
      <th scope="row">Created At</th>
      <td><%= @command.created_at %></td>
    </tr>

    <tr>
      <th scope="row">aggregate_id</th>
      <td><%= @command.aggregate_id %></td>
    </tr>

    <tr>
      <th scope="row">event_json</th>
      <td>
        <code>
          <%= simple_format JSON.pretty_generate(JSON.parse @command.command_json) %>
        </code>
      </td>
    </tr>
  </tbody>
</table>

app/views/sequent/events/_event_record.html.erb
<tr>
  <th scope="row"> <%= event_record.id %></th>
  <td><%= link_to event_record.event_type, event_path(event_record) %></td>
  <td><%= link_to event_record.aggregate_id, stream_events_path(stream_id: event_record.stream_record_id) %></td>
  <td><%= event_record.sequence_number %></td>
  <td>
    <code>
      <%= JSON.parse(event_record.event_json).except("sequence_number", "aggregate_id").to_json %>
    </code>
  </td>
</tr>

app/views/sequent/events/index.html.erb
<%= link_to "Aggregate:" + params[:aggregate_id], url_for(aggregate_id: nil), class: 'badge badge-secondary' if params[:aggregate_id] %>
<%= link_to "Stream: " + params[:stream_id], url_for(stream_id: nil), class: 'badge badge-secondary' if params[:stream_id] %>

<table class="table table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col"> id</th>
      <th scope="col"> event_type</th>
      <th scope="col"> aggregate_id</th>
      <th scope="col"> sequence_number</th>
      <th scope="col"> event_json</th>
    </tr>
  </thead>

  <% @grouped_events.each do |command, events| %>
    <thead class="thead-light">
      <tr>
        <th colspan="4">
          <%= link_to command.command_type, command_path(command) %>
        </th>
        <th colspan="4">
          User: <%= command.user_id %>
        </th>
      </tr>
    </thead>
    <tbody class="events">
      <%= render collection: events, partial: 'event_record' %>
    </tbody>
  <% end %>
</table>

app/views/sequent/events/show.html.erb
<table class="table table-bordered">
  <thead  class="thead-dark">
    <tr>
      <th scope="col">Attribute</th>
      <th scope="col">Value</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <th scope="row">Id</th>
      <td><%= @event.id %></td>
    </tr>

    <tr>
      <th scope="row">Type</th>
      <td><%= @event.event_type %></td>
    </tr>

    <tr>
      <th scope="row">Aggregate Id</th>
      <td><%= @event.aggregate_id %></td>
    </tr>

    <tr>
      <th scope="row">Sequence Number</th>
      <td><%= @event.sequence_number %></td>
    </tr>

    <tr>
      <th scope="row">Command</th>
      <td><%= link_to @event.command_record.command_type, command_path(@event.command_record) %></td>
    </tr>

    <tr>
      <th scope="row">JSON</th>
      <td>
        <code>
          <%= simple_format JSON.pretty_generate(JSON.parse @event.event_json) %>
        </code>
      </td>
    </tr>
  </tbody>
</table>

app/views/sequent/streams/_stream_record.html.erb
<tr>
  <th scope="row"> <%= stream_record.id %></th>
  <td><%= link_to stream_record.aggregate_id, stream_events_path(stream_record.id) %></td>
  <td><%= link_to stream_record.aggregate_type, url_for(aggregate_type: stream_record.aggregate_type) %></td>
  <td>
    <code>
      <%= stream_record.attributes.to_json %>
    </code>
  </td>
</tr>

app/views/sequent/streams/index.html.erb
<%= link_to "Type: " + params[:aggregate_type], url_for(aggregate_type: nil), class: 'badge badge-secondary' if params[:aggregate_type] %>

<table class="table table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">id</th>
      <th scope="col">aggregate_id</th>
      <th scope="col">aggregate_type</th>
      <th scope="col">data</th>
    </tr>
  </thead>

  <tbody class="events">
    <%= render partial: 'stream_record', collection: @streams %>
  </tbody>
</table>